---
- name: create www/vr directory
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ installation_os_user }}'
  with_items:
    - '{{ webvr_dir }}'
    - '{{ webvr_dir }}/assets/'
    - '{{ webvr_dir }}/assets/lib'
    - '{{ webvr_dir }}/assets/models'
    - '{{ webvr_dir }}/assets/images'
    - '{{ webvr_dir }}/assets/textures'


- name: Download aframe libraries
  get_url:
    url: '{{ item }}'
    dest: '{{ webvr_dir }}/assets/lib'
  with_items:
    - https://aframe.io/releases/0.9.2/aframe.min.js
    - https://unpkg.com/browse/aframe-template-component/dist/aframe-template-component.min.js
    - https://unpkg.com/aframe-event-set-component/dist/aframe-event-set-component.min.js
    - https://unpkg.com/browse/aframe-extras/dist/aframe-extras.min.js
